# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 409)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 344))
        self.groupBox_2.setMaximumSize(QtCore.QSize(500, 400))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Latin Modern Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_3.setAcceptDrops(False)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 530, 342))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")

        self.pushButton_next2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_next2.setObjectName("pushButton_next2")
        self.gridLayout_4.addWidget(self.pushButton_next2, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.pushButton_back2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_back2.setObjectName("pushButton_back2")
        self.gridLayout_4.addWidget(self.pushButton_back2, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 4, 0, 1, 2)

        self.label_Indiq2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Indiq2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_Indiq2.setObjectName("label_Indiq2")
        self.gridLayout_5.addWidget(self.label_Indiq2, 2, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_sample = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_sample.setObjectName("label_sample")
        self.horizontalLayout_2.addWidget(self.label_sample)
        self.lineEdit_sample = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_sample.setObjectName("lineEdit_sample")
        self.horizontalLayout_2.addWidget(self.lineEdit_sample)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_library = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_library.setObjectName("label_library")
        self.horizontalLayout.addWidget(self.label_library)
        self.lineEdit_library = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_library.setObjectName("lineEdit_library")
        self.horizontalLayout.addWidget(self.lineEdit_library)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.label_rgid = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_rgid.setObjectName("label_rgid")
        self.horizontalLayout_5.addWidget(self.label_rgid)
        self.lineEdit_rgid = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_rgid.setObjectName("lineEdit_rgid")
        self.horizontalLayout_5.addWidget(self.lineEdit_rgid)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_rgpu = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_rgpu.setObjectName("label_rgpu")
        self.horizontalLayout_4.addWidget(self.label_rgpu)
        self.lineEdit_rgpu = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_rgpu.setObjectName("lineEdit_rgpu")
        self.horizontalLayout_4.addWidget(self.lineEdit_rgpu)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_plateforme = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_plateforme.setObjectName("label_plateforme")
        self.horizontalLayout_3.addWidget(self.label_plateforme)
        self.lineEdit_plateforme = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_plateforme.setObjectName("lineEdit_plateforme")
        self.horizontalLayout_3.addWidget(self.lineEdit_plateforme)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 3, 0, 1, 2)
        self.label_BGI = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_BGI.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_BGI.setMidLineWidth(0)
        self.label_BGI.setIndent(1)
        self.label_BGI.setOpenExternalLinks(False)
        self.label_BGI.setObjectName("label_BGI")
        self.gridLayout_5.addWidget(self.label_BGI, 1, 0, 1, 1)
        self.label_etape2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_etape2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_etape2.setObjectName("label_etape2")
        self.gridLayout_5.addWidget(self.label_etape2, 0, 0, 1, 2)
        self.label_BGI.raise_()
        self.label_Indiq2.raise_()
        self.label_etape2.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Andalusian Mapping</p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Acceuil"))
        self.pushButton.setText(_translate("MainWindow", "Nouvelle analyse"))
        self.pushButton_2.setText(_translate("MainWindow", "Charger une analyse"))
        self.pushButton_3.setText(_translate("MainWindow", "Résultats"))
        self.pushButton_5.setText(_translate("MainWindow", "About - Author"))
        self.pushButton_next2.setText(_translate("MainWindow", "Next"))
        self.pushButton_back2.setText(_translate("MainWindow", "Back"))
        self.label_Indiq2.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-style:italic;\">Les noms des fichiers serons construit comme suis : {FlowCellID}-{sampleID}_Lane </span></p></body></html>"))
        self.label_sample.setText(_translate("MainWindow", "Sample :         "))
        self.lineEdit_sample.setText(_translate("MainWindow", "e.g. mf76"))
        self.label_library.setText(_translate("MainWindow", "Library :          "))
        self.lineEdit_library.setText(_translate("MainWindow", "e.g. mf76_LB1"))
        self.label_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose \'Flow Cell ID\'_\'sample\'</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "?"))
        self.label_rgid.setText(_translate("MainWindow", "RGID :         "))
        self.label_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>Choose \'Flow Cell ID\'_\'Lane\'_\'sample\'</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "?"))
        self.label_rgpu.setText(_translate("MainWindow", "RGPU :        "))
        self.label_plateforme.setText(_translate("MainWindow", "Plateforme : "))
        self.lineEdit_plateforme.setText(_translate("MainWindow", "e.g. ILLUMINA"))
        self.label_BGI.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\"># BGI </span></p></body></html>"))
        self.label_etape2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Formulaire : étape 2 sur 3</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
