# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm4.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 435)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 344))
        self.groupBox_2.setMaximumSize(QtCore.QSize(500, 400))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_titre = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Latin Modern Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_titre.setFont(font)
        self.label_titre.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_titre.setAcceptDrops(False)
        self.label_titre.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_titre.setObjectName("label_titre")
        self.gridLayout.addWidget(self.label_titre, 0, 0, 1, 1)
        self.pushButton_acceuil = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_acceuil.setObjectName("pushButton_acceuil")
        self.gridLayout.addWidget(self.pushButton_acceuil, 1, 0, 1, 1)
        self.pushButton_newAnalyse = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_newAnalyse.setObjectName("pushButton_newAnalyse")
        self.gridLayout.addWidget(self.pushButton_newAnalyse, 2, 0, 1, 1)
        self.pushButton_oldAnalise = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_oldAnalise.setObjectName("pushButton_oldAnalise")
        self.gridLayout.addWidget(self.pushButton_oldAnalise, 3, 0, 1, 1)
        self.pushButton_resultat = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_resultat.setObjectName("pushButton_resultat")
        self.gridLayout.addWidget(self.pushButton_resultat, 4, 0, 1, 1)
        self.pushButton_author = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_author.setObjectName("pushButton_author")
        self.gridLayout.addWidget(self.pushButton_author, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 491, 368))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")


        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_etape4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_etape4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_etape4.setObjectName("label_etape4")
        self.gridLayout_2.addWidget(self.label_etape4, 0, 0, 1, 1)
        self.label_titre4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_titre4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_titre4.setObjectName("label_titre4")
        self.gridLayout_2.addWidget(self.label_titre4, 1, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_listScaff = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_listScaff.setObjectName("label_listScaff")
        self.horizontalLayout_18.addWidget(self.label_listScaff)
        self.lineEdit_listScaff = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_listScaff.setText("")
        self.lineEdit_listScaff.setObjectName("lineEdit_listScaff")
        self.horizontalLayout_18.addWidget(self.lineEdit_listScaff)
        self.toolButton_listScaff = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_listScaff.setObjectName("toolButton_listScaff")
        self.horizontalLayout_18.addWidget(self.toolButton_listScaff)
        self.gridLayout_2.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_InvarScaf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_InvarScaf.setObjectName("label_InvarScaf")
        self.horizontalLayout_11.addWidget(self.label_InvarScaf)
        self.lineEdit_InvarScaf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_InvarScaf.setText("")
        self.lineEdit_InvarScaf.setObjectName("lineEdit_InvarScaf")
        self.horizontalLayout_11.addWidget(self.lineEdit_InvarScaf)
        self.toolButton_InvarScaf = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_InvarScaf.setObjectName("toolButton_InvarScaf")
        self.horizontalLayout_11.addWidget(self.toolButton_InvarScaf)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.label_warnScaf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_warnScaf.setObjectName("label_warnScaf")
        self.horizontalLayout_13.addWidget(self.label_warnScaf)
        self.lineEdit_warnScaf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_warnScaf.setText("")
        self.lineEdit_warnScaf.setObjectName("lineEdit_warnScaf")
        self.horizontalLayout_13.addWidget(self.lineEdit_warnScaf)
        self.toolButton_warnScaf = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_warnScaf.setObjectName("toolButton_warnScaf")
        self.horizontalLayout_13.addWidget(self.toolButton_warnScaf)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(470, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_back4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_back4.setObjectName("pushButton_back4")
        self.horizontalLayout.addWidget(self.pushButton_back4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_runAnalysis = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_runAnalysis.setMinimumSize(QtCore.QSize(116, 0))
        self.pushButton_runAnalysis.setMaximumSize(QtCore.QSize(50, 30))
        self.pushButton_runAnalysis.setSizeIncrement(QtCore.QSize(1, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_runAnalysis.setPalette(palette)
        self.pushButton_runAnalysis.setObjectName("pushButton_runAnalysis")
        self.horizontalLayout.addWidget(self.pushButton_runAnalysis)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titre.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Andalusian Mapping</p></body></html>"))
        self.pushButton_acceuil.setText(_translate("MainWindow", "Acceuil"))
        self.pushButton_newAnalyse.setText(_translate("MainWindow", "Nouvelle analyse"))
        self.pushButton_oldAnalise.setText(_translate("MainWindow", "Charger une analyse"))
        self.pushButton_resultat.setText(_translate("MainWindow", "Résultats"))
        self.pushButton_author.setText(_translate("MainWindow", "About - Author"))
        self.label_etape4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Formulaire : étape 4 sur 4</span></p></body></html>"))
        self.label_titre4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\"># Additionnal files</span></p></body></html>"))
        self.label_listScaff.setText(_translate("MainWindow", "List of scaffolds ID and their size :"))
        self.toolButton_listScaff.setText(_translate("MainWindow", "..."))
        self.label_InvarScaf.setText(_translate("MainWindow", "\"Invariant\" Scaffolds :                       "))
        self.toolButton_InvarScaf.setText(_translate("MainWindow", "..."))
        self.label_17.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">list of scaffolds you want to test even if they are not linked to your mutation. (e.g. False-positive or so-far-unlinked scaffolds)</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "?"))
        self.label_warnScaf.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_warnScaf.setText(_translate("MainWindow", "Warning Scaffolds :                       "))
        self.toolButton_warnScaf.setText(_translate("MainWindow", "..."))
        self.pushButton_back4.setText(_translate("MainWindow", "Back"))
        self.pushButton_runAnalysis.setText(_translate("MainWindow", "Run Analysis"))
