# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm3.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 344))
        self.groupBox_2.setMaximumSize(QtCore.QSize(500, 400))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Latin Modern Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_3.setAcceptDrops(False)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 4, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 445, 542))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_etape3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_etape3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_etape3.setObjectName("label_etape3")
        self.gridLayout_3.addWidget(self.label_etape3, 0, 0, 1, 1)
        self.label_titre3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_titre3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_titre3.setObjectName("label_titre3")
        self.gridLayout_3.addWidget(self.label_titre3, 1, 0, 1, 1)
        self.label_indique3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_indique3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_indique3.setObjectName("label_indique3")
        self.gridLayout_3.addWidget(self.label_indique3, 2, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_dbsnp = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_dbsnp.setObjectName("label_dbsnp")
        self.horizontalLayout_17.addWidget(self.label_dbsnp)
        self.lineEdit_dbsnp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_dbsnp.setObjectName("lineEdit_dbsnp")
        self.horizontalLayout_17.addWidget(self.lineEdit_dbsnp)
        self.toolButton_11 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_11.setObjectName("toolButton_11")
        self.horizontalLayout_17.addWidget(self.toolButton_11)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 3, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_listScaff = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_listScaff.setObjectName("label_listScaff")
        self.horizontalLayout_18.addWidget(self.label_listScaff)
        self.lineEdit_listScaff = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_listScaff.setObjectName("lineEdit_listScaff")
        self.horizontalLayout_18.addWidget(self.lineEdit_listScaff)
        self.toolButton_12 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_18.addWidget(self.toolButton_12)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 4, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_InvarScaf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_InvarScaf.setObjectName("label_InvarScaf")
        self.horizontalLayout_11.addWidget(self.label_InvarScaf)
        self.lineEdit_InvarScaf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_InvarScaf.setObjectName("lineEdit_InvarScaf")
        self.horizontalLayout_11.addWidget(self.lineEdit_InvarScaf)
        self.toolButton_7 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_11.addWidget(self.toolButton_7)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 5, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.label_warnScaf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_warnScaf.setObjectName("label_warnScaf")
        self.horizontalLayout_13.addWidget(self.label_warnScaf)
        self.lineEdit_warnScaf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_warnScaf.setObjectName("lineEdit_warnScaf")
        self.horizontalLayout_13.addWidget(self.lineEdit_warnScaf)
        self.toolButton_9 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_9.setObjectName("toolButton_9")
        self.horizontalLayout_13.addWidget(self.toolButton_9)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 6, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_Contvcf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Contvcf.setObjectName("label_Contvcf")
        self.horizontalLayout_12.addWidget(self.label_Contvcf)
        self.lineEdit_Contvcf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Contvcf.setObjectName("lineEdit_Contvcf")
        self.horizontalLayout_12.addWidget(self.lineEdit_Contvcf)
        self.toolButton_8 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_12.addWidget(self.toolButton_8)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 7, 0, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_Mappvcf = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_Mappvcf.setObjectName("label_Mappvcf")
        self.horizontalLayout_14.addWidget(self.label_Mappvcf)
        self.lineEdit_Mappvcf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Mappvcf.setObjectName("lineEdit_Mappvcf")
        self.horizontalLayout_14.addWidget(self.lineEdit_Mappvcf)
        self.toolButton_10 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_14.addWidget(self.toolButton_10)
        self.gridLayout_3.addLayout(self.horizontalLayout_14, 8, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_backStrainId = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_backStrainId.setObjectName("label_backStrainId")
        self.horizontalLayout_10.addWidget(self.label_backStrainId)
        self.lineEdit_backStrainId = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_backStrainId.setObjectName("lineEdit_backStrainId")
        self.horizontalLayout_10.addWidget(self.lineEdit_backStrainId)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 9, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_16.addWidget(self.label_20)
        self.label_mappStrainId = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_mappStrainId.setObjectName("label_mappStrainId")
        self.horizontalLayout_16.addWidget(self.label_mappStrainId)
        self.lineEdit_mappStrainId = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_mappStrainId.setObjectName("lineEdit_mappStrainId")
        self.horizontalLayout_16.addWidget(self.lineEdit_mappStrainId)
        self.gridLayout_3.addLayout(self.horizontalLayout_16, 10, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.pushButton_runAnalysis = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_runAnalysis.setMinimumSize(QtCore.QSize(116, 0))
        self.pushButton_runAnalysis.setMaximumSize(QtCore.QSize(50, 30))
        self.pushButton_runAnalysis.setSizeIncrement(QtCore.QSize(1, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_runAnalysis.setPalette(palette)
        self.pushButton_runAnalysis.setObjectName("pushButton_runAnalysis")
        self.horizontalLayout_15.addWidget(self.pushButton_runAnalysis)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 11, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Andalusian Mapping</p></body></html>"))
        self.pushButton_4.setText(_translate("MainWindow", "Acceuil"))
        self.pushButton.setText(_translate("MainWindow", "Nouvelle analyse"))
        self.pushButton_2.setText(_translate("MainWindow", "Charger une analyse"))
        self.pushButton_3.setText(_translate("MainWindow", "Résultats"))
        self.pushButton_5.setText(_translate("MainWindow", "About - Author"))
        self.label_etape3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Formulaire : étape 3 sur 3</span></p></body></html>"))
        self.label_titre3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\"># DATA required for mapping by sequencing</span></p></body></html>"))
        self.label_indique3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">All this file should be stored in NNNN/path/to/Andalousian-mapping/data/</span></p></body></html>"))
        self.label_dbsnp.setText(_translate("MainWindow", "dbSNP of the mapping strain :        "))
        self.lineEdit_dbsnp.setText(_translate("MainWindow", "dbSNP_JU170_v2.0.vcf "))
        self.toolButton_11.setText(_translate("MainWindow", "..."))
        self.label_listScaff.setText(_translate("MainWindow", "List of scaffolds ID and their size :"))
        self.lineEdit_listScaff.setText(_translate("MainWindow", "nOt.2.0_Scaff-size.tsv"))
        self.toolButton_12.setText(_translate("MainWindow", "..."))
        self.label_InvarScaf.setText(_translate("MainWindow", "\"Invariant\" Scaffolds :                       "))
        self.lineEdit_InvarScaf.setText(_translate("MainWindow", "JU170_InvariantScaffold.interval_list"))
        self.toolButton_7.setText(_translate("MainWindow", "..."))
        self.label_17.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">list of scaffolds you want to test even if they are not linked to your mutation. (e.g. False-positive or so-far-unlinked scaffolds)</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "?"))
        self.label_warnScaf.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_warnScaf.setText(_translate("MainWindow", "Warning Scaffolds :                       "))
        self.lineEdit_warnScaf.setText(_translate("MainWindow", "JU170_FalsePositiveScaffold.list"))
        self.toolButton_9.setText(_translate("MainWindow", "..."))
        self.label_Contvcf.setText(_translate("MainWindow", "Control gVCFs :                                  "))
        self.lineEdit_Contvcf.setText(_translate("MainWindow", "CEW1.gVCF.vcf"))
        self.toolButton_8.setText(_translate("MainWindow", "..."))
        self.label_Mappvcf.setText(_translate("MainWindow", "Mapping_gVCF :                                "))
        self.lineEdit_Mappvcf.setText(_translate("MainWindow", "JU170.gVCF.vcf"))
        self.toolButton_10.setText(_translate("MainWindow", "..."))
        self.label_backStrainId.setText(_translate("MainWindow", "Background strain ID :                    "))
        self.lineEdit_backStrainId.setText(_translate("MainWindow", "CEW1"))
        self.label_20.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic;\">It should be the same as RGSM appearing in the $Mapping_gVCF (determine with &quot;Read Group&quot; information during analysis)</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "?"))
        self.label_mappStrainId.setText(_translate("MainWindow", "Mapping strain ID:                       "))
        self.lineEdit_mappStrainId.setText(_translate("MainWindow", "JU170"))
        self.pushButton_runAnalysis.setText(_translate("MainWindow", "Run Analysis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

