# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm1ListR.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 661)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 344))
        self.groupBox_2.setMaximumSize(QtCore.QSize(500, 400))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_acceuil = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_acceuil.setObjectName("pushButton_acceuil")
        self.gridLayout_2.addWidget(self.pushButton_acceuil, 1, 0, 1, 1)
        self.pushButton_newAnalyse = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_newAnalyse.setObjectName("pushButton_newAnalyse")
        self.gridLayout_2.addWidget(self.pushButton_newAnalyse, 2, 0, 1, 1)
        self.pushButton_oldAnalise = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_oldAnalise.setObjectName("pushButton_oldAnalise")
        self.gridLayout_2.addWidget(self.pushButton_oldAnalise, 3, 0, 1, 1)
        self.label_titre = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Latin Modern Mono")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_titre.setFont(font)
        self.label_titre.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label_titre.setAcceptDrops(False)
        self.label_titre.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_titre.setObjectName("label_titre")
        self.gridLayout_2.addWidget(self.label_titre, 0, 0, 1, 1)
        self.pushButton_resultat = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_resultat.setObjectName("pushButton_resultat")
        self.gridLayout_2.addWidget(self.pushButton_resultat, 4, 0, 1, 1)
        self.pushButton_author = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_author.setObjectName("pushButton_author")
        self.gridLayout_2.addWidget(self.pushButton_author, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 594))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_etape1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_etape1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_etape1.setObjectName("label_etape1")
        self.gridLayout_3.addWidget(self.label_etape1, 0, 0, 1, 1)
        self.label_titre1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_titre1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_titre1.setObjectName("label_titre1")
        self.gridLayout_3.addWidget(self.label_titre1, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_nom = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_nom.setObjectName("label_nom")
        self.horizontalLayout_11.addWidget(self.label_nom)
        self.lineEdit_nom = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_nom.setObjectName("lineEdit_nom")
        self.horizontalLayout_11.addWidget(self.lineEdit_nom)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 2, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_genRef = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_genRef.setObjectName("label_genRef")
        self.horizontalLayout_10.addWidget(self.label_genRef)
        self.lineEdit_genRef = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_genRef.setObjectName("lineEdit_genRef")
        self.horizontalLayout_10.addWidget(self.lineEdit_genRef)
        self.toolButton_genRef = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_genRef.setObjectName("toolButton_genRef")
        self.horizontalLayout_10.addWidget(self.toolButton_genRef)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_r1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_r1.setObjectName("label_r1")
        self.horizontalLayout.addWidget(self.label_r1)
        self.lineEdit_r1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_r1.setObjectName("lineEdit_r1")
        self.horizontalLayout.addWidget(self.lineEdit_r1)
        self.toolButton_r1 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_r1.setObjectName("toolButton_r1")
        self.horizontalLayout.addWidget(self.toolButton_r1)
        self.gridLayout_3.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_r2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_r2.setObjectName("label_r2")
        self.horizontalLayout_9.addWidget(self.label_r2)
        self.lineEdit_r2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_r2.setObjectName("lineEdit_r2")
        self.horizontalLayout_9.addWidget(self.lineEdit_r2)
        self.toolButton_r2 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_r2.setObjectName("toolButton_r2")
        self.horizontalLayout_9.addWidget(self.toolButton_r2)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_r3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_r3.setObjectName("label_r3")
        self.horizontalLayout_2.addWidget(self.label_r3)
        self.lineEdit_r3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_r3.setObjectName("lineEdit_r3")
        self.horizontalLayout_2.addWidget(self.lineEdit_r3)
        self.toolButton_r3 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_r3.setObjectName("toolButton_r3")
        self.horizontalLayout_2.addWidget(self.toolButton_r3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 6, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_r4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_r4.setObjectName("label_r4")
        self.horizontalLayout_4.addWidget(self.label_r4)
        self.lineEdit_r4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_r4.setObjectName("lineEdit_r4")
        self.horizontalLayout_4.addWidget(self.lineEdit_r4)
        self.toolButton_r4 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_r4.setObjectName("toolButton_r4")
        self.horizontalLayout_4.addWidget(self.toolButton_r4)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 7, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_r5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_r5.setObjectName("label_r5")
        self.horizontalLayout_5.addWidget(self.label_r5)
        self.lineEdit_r5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_r5.setObjectName("lineEdit_r5")
        self.horizontalLayout_5.addWidget(self.lineEdit_r5)
        self.toolButton_r5 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_r5.setObjectName("toolButton_r5")
        self.horizontalLayout_5.addWidget(self.toolButton_r5)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 8, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_r6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_r6.setObjectName("label_r6")
        self.horizontalLayout_6.addWidget(self.label_r6)
        self.lineEdit_r6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_r6.setObjectName("lineEdit_r6")
        self.horizontalLayout_6.addWidget(self.lineEdit_r6)
        self.toolButton_r6 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_r6.setObjectName("toolButton_r6")
        self.horizontalLayout_6.addWidget(self.toolButton_r6)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 9, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_r7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_r7.setObjectName("label_r7")
        self.horizontalLayout_7.addWidget(self.label_r7)
        self.lineEdit_r7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_r7.setObjectName("lineEdit_r7")
        self.horizontalLayout_7.addWidget(self.lineEdit_r7)
        self.toolButton_r7 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_r7.setObjectName("toolButton_r7")
        self.horizontalLayout_7.addWidget(self.toolButton_r7)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 10, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_r8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_r8.setObjectName("label_r8")
        self.horizontalLayout_8.addWidget(self.label_r8)
        self.lineEdit_r8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_r8.setObjectName("lineEdit_r8")
        self.horizontalLayout_8.addWidget(self.lineEdit_r8)
        self.toolButton_r8 = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.toolButton_r8.setObjectName("toolButton_r8")
        self.horizontalLayout_8.addWidget(self.toolButton_r8)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 11, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.pushButton_plus = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_plus.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton_plus.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.horizontalLayout_12.addWidget(self.pushButton_plus)
        self.pushButton_moins = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_moins.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_moins.setObjectName("pushButton_moins")
        self.horizontalLayout_12.addWidget(self.pushButton_moins)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 12, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_next1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_next1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_next1.setObjectName("pushButton_next1")
        self.horizontalLayout_3.addWidget(self.pushButton_next1)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 13, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_acceuil.setText(_translate("MainWindow", "Acceuil"))
        self.pushButton_newAnalyse.setText(_translate("MainWindow", "Nouvelle analyse"))
        self.pushButton_oldAnalise.setText(_translate("MainWindow", "Charger une analyse"))
        self.label_titre.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Andalusian Mapping</p></body></html>"))
        self.pushButton_resultat.setText(_translate("MainWindow", "Résultats"))
        self.pushButton_author.setText(_translate("MainWindow", "About - Author"))
        self.label_etape1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic;\">Formulaire : étape 1 sur 3</span></p></body></html>"))
        self.label_titre1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\"># Your inputs :</span></p></body></html>"))
        self.label_nom.setText(_translate("MainWindow", "Nom de l\'analyse :             "))
        self.label_genRef.setText(_translate("MainWindow", "Génome de référence   : "))
        self.toolButton_genRef.setText(_translate("MainWindow", "..."))
        self.label_r1.setText(_translate("MainWindow", "[1] Read   : "))
        self.toolButton_r1.setText(_translate("MainWindow", "..."))
        self.label_r2.setText(_translate("MainWindow", "[2] Read   : "))
        self.toolButton_r2.setText(_translate("MainWindow", "..."))
        self.label_r3.setText(_translate("MainWindow", "[3] Read   : "))
        self.toolButton_r3.setText(_translate("MainWindow", "..."))
        self.label_r4.setText(_translate("MainWindow", "[4] Read   : "))
        self.toolButton_r4.setText(_translate("MainWindow", "..."))
        self.label_r5.setText(_translate("MainWindow", "[5] Read   : "))
        self.toolButton_r5.setText(_translate("MainWindow", "..."))
        self.label_r6.setText(_translate("MainWindow", "[6] Read   : "))
        self.toolButton_r6.setText(_translate("MainWindow", "..."))
        self.label_r7.setText(_translate("MainWindow", "[7] Read   : "))
        self.toolButton_r7.setText(_translate("MainWindow", "..."))
        self.label_r8.setText(_translate("MainWindow", "[8] Read   : "))
        self.toolButton_r8.setText(_translate("MainWindow", "..."))
        self.pushButton_plus.setText(_translate("MainWindow", "+"))
        self.pushButton_moins.setText(_translate("MainWindow", "-"))
        self.pushButton_next1.setText(_translate("MainWindow", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
